spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab
    username: postgres
    password: Timur1883
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  address: 0.0.0.0
  port: 8082
rabbit:
  hostname: localhost
  username: guest
  password: guest
  virtual-host: /
  exchange-name: lab